OPT = -O3 -std=c++14
all: HD7round encrypt HD5round

HD7round: HD7round.cpp
	g++ HD7round.cpp -o HD7round $(OPT)

HD5round: HD5round.cpp
	g++ HD5round.cpp -o HD5round $(OPT)

encrypt: encrypt.cpp
	g++ encrypt.cpp -o encrypt $(OPT)



